AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  actualPdfHandler:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.8
      CodeUri: .
      Description: ''
      MemorySize: 128
      Timeout: 3
      Role: >-
        arn:aws:iam::251091134017:role/service-role/actualPdfHandler-role-hmp25oto
      Events:
        SNS1:
          Type: SNS
          Properties:
            Topic:
              Ref: SNSTopic1
      Environment:
        Variables:
          QueueURL: >-
            https://sqs.us-east-1.amazonaws.com/251091134017/attachments_info_queue_
  SNSTopic1:
    Type: 'AWS::SNS::Topic'
