AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  amplifys3uploaderuidevUpdateRolesWithIDPFunctixsoy1kI7WJcF:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: index.handler
      Runtime: nodejs12.x
      CodeUri: .
      Description: ''
      MemorySize: 128
      Timeout: 300
      Role: >-
        arn:aws:iam::251091134017:role/amplify-s3uploaderui-dev-65310-authRole-idp
      Tags:
        'user:Application': s3uploaderui
        'user:Stack': dev
