AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  PciLambdaHandler:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.8
      CodeUri: .
      Description: ''
      MemorySize: 128
      Timeout: 3
      Role: >-
        arn:aws:iam::251091134017:role/service-role/PciLambdaHandler-role-09ft3b8l
      Events:
        BucketEvent1:
          Type: S3
          Properties:
            Bucket:
              Ref: Bucket1
            Events:
              - 's3:ObjectCreated:*'
            Filter:
              S3Key:
                Rules:
                  - Name: prefix
                    Value: images/
      Environment:
        Variables:
          QueueURL: >-
            https://sqs.us-east-1.amazonaws.com/251091134017/attachments_info_queue_
      Layers:
        - 'arn:aws:lambda:us-east-1:251091134017:layer:ImageWandLayer:4'
  Bucket1:
    Type: 'AWS::S3::Bucket'
