AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  S3Triggerb98b6c06dev:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: index.handler
      Runtime: nodejs14.x
      CodeUri: .
      Description: ''
      MemorySize: 128
      Timeout: 25
      Role: 'arn:aws:iam::251091134017:role/S3Triggerb98b6c06LambdaRoleb98b6c06-dev'
      Environment:
        Variables:
          ENV: dev
      Tags:
        'user:Application': s3uploaderui
        'user:Stack': dev
